name: actions usefulness
on: [push]
jobs:
    test-actions:
        runs-on: [ubuntu-latest]
        steps:
        - name: checkout action
          uses: actions/checkout@v4
        - name: print repersitory
          run: ls -l
          

          

